// Story world 2: level-specific vocabulary. Elementary maps have 20 words; middle-school maps have 30 words.
(() => {
  const maps = [
    {name:'사원으로 가는 다리',desc:'첫 다리를 건너 사원으로 향해요',
      elementary:[['bridge','명','다리'],['road','명','길'],['river','명','강'],['water','명','물'],['boat','명','배'],['walk','동','걷다'],['go','동','가다'],['come','동','오다'],['stop','동','멈추다'],['run','동','달리다'],['foot','명','발'],['hand','명','손'],['friend','명','친구'],['hello','감','안녕'],['ready','형','준비된'],['slow','형','느린'],['fast','형','빠른'],['near','부','가까이'],['far','부','멀리'],['together','부','함께']],
      middle:[['entrance','명','입구'],['journey','명','여정'],['destination','명','목적지'],['direction','명','방향'],['distance','명','거리'],['route','명','경로'],['cross','동','건너다'],['approach','동','다가가다'],['depart','동','출발하다'],['arrive','동','도착하다'],['follow','동','따라가다'],['guide','동','안내하다'],['connect','동','연결하다'],['continue','동','계속하다'],['narrow','형','좁은'],['steep','형','가파른'],['nearby','형','근처의'],['ahead','부','앞으로'],['beyond','전','너머에'],['toward','전','~을 향하여'],["travel","동","여행하다"],["trip","명","여행"],["vehicle","명","탈것"],["traffic","명","교통"],["sign","명","표지판"],["pedestrian","명","보행자"],["passenger","명","승객"],["forward","부","앞쪽으로"],["backward","부","뒤쪽으로"],["distant","형","멀리 떨어진"]]},
    {name:'빛나는 숲길',desc:'나무 사이에서 빛나는 크리스탈을 찾아요',
      elementary:[['tree','명','나무'],['leaf','명','나뭇잎'],['flower','명','꽃'],['grass','명','풀'],['forest','명','숲'],['bird','명','새'],['rabbit','명','토끼'],['frog','명','개구리'],['butterfly','명','나비'],['ant','명','개미'],['green','형','초록색의'],['yellow','형','노란색의'],['small','형','작은'],['big','형','큰'],['tall','형','키가 큰'],['look','동','보다'],['listen','동','듣다'],['find','동','찾다'],['sit','동','앉다'],['stand','동','서다']],
      middle:[['environment','명','환경'],['nature','명','자연'],['branch','명','나뭇가지'],['root','명','뿌리'],['seed','명','씨앗'],['soil','명','흙'],['insect','명','곤충'],['habitat','명','서식지'],['wildlife','명','야생 동물'],['shade','명','그늘'],['grow','동','자라다'],['bloom','동','꽃이 피다'],['protect','동','보호하다'],['observe','동','관찰하다'],['discover','동','발견하다'],['breathe','동','숨 쉬다'],['fresh','형','신선한'],['wild','형','야생의'],['peaceful','형','평화로운'],['natural','형','자연의'],["plant","명","식물"],["bush","명","덤불"],["bark","명","나무껍질"],["wood","명","목재"],["oxygen","명","산소"],["creature","명","생물"],["species","명","종"],["survive","동","살아남다"],["disappear","동","사라지다"],["gentle","형","온화한"]]},
    {name:'폭포 앞 크리스탈',desc:'폭포 소리를 들으며 단어를 연결해요',
      elementary:[['rain','명','비'],['snow','명','눈'],['wind','명','바람'],['cloud','명','구름'],['sun','명','태양'],['sky','명','하늘'],['sea','명','바다'],['lake','명','호수'],['fish','명','물고기'],['rock','명','바위'],['hot','형','더운'],['cold','형','추운'],['warm','형','따뜻한'],['cool','형','시원한'],['wet','형','젖은'],['dry','형','마른'],['swim','동','수영하다'],['wash','동','씻다'],['drink','동','마시다'],['rainbow','명','무지개']],
      middle:[['waterfall','명','폭포'],['stream','명','시냇물'],['current','명','물의 흐름'],['surface','명','표면'],['depth','명','깊이'],['temperature','명','온도'],['weather','명','날씨'],['climate','명','기후'],['mist','명','안개'],['wave','명','파도'],['flow','동','흐르다'],['float','동','뜨다'],['sink','동','가라앉다'],['freeze','동','얼다'],['melt','동','녹다'],['reflect','동','비추다'],['refresh','동','상쾌하게 하다'],['clear','형','맑은'],['shallow','형','얕은'],['powerful','형','강력한'],["spray","명","물보라"],["drop","명","물방울"],["pond","명","연못"],["shore","명","물가"],["flood","명","홍수"],["drought","명","가뭄"],["liquid","명","액체"],["splash","동","물을 튀기다"],["pour","동","쏟다"],["smooth","형","매끄러운"]]},
    {name:'굽이진 돌길',desc:'굽이진 길에서 다음 길목을 찾아요',
      elementary:[['left','명','왼쪽'],['right','명','오른쪽'],['front','명','앞쪽'],['back','명','뒤쪽'],['top','명','맨 위'],['bottom','명','맨 아래'],['up','부','위로'],['down','부','아래로'],['inside','부','안에'],['outside','부','밖에'],['turn','동','돌다'],['open','동','열다'],['close','동','닫다'],['push','동','밀다'],['pull','동','당기다'],['door','명','문'],['window','명','창문'],['wall','명','벽'],['step','명','걸음'],['map','명','지도']],
      middle:[['path','명','오솔길'],['corner','명','모퉁이'],['intersection','명','교차로'],['position','명','위치'],['boundary','명','경계'],['passage','명','통로'],['obstacle','명','장애물'],['balance','명','균형'],['slope','명','비탈'],['height','명','높이'],['climb','동','오르다'],['avoid','동','피하다'],['reach','동','도달하다'],['explore','동','탐험하다'],['lead','동','이끌다'],['return','동','돌아오다'],['straight','형','곧은'],['opposite','형','반대편의'],['careful','형','조심스러운'],['safely','부','안전하게'],["trail","명","산길"],["valley","명","계곡"],["cliff","명","절벽"],["cave","명","동굴"],["directional","형","방향을 나타내는"],["rough","형","거친"],["slippery","형","미끄러운"],["wander","동","돌아다니다"],["slide","동","미끄러지다"],["measure","동","측정하다"]]},
    {name:'구름 다리의 수호석',desc:'다리 위 수호석에 담긴 단어를 깨워요',
      elementary:[['family','명','가족'],['mother','명','어머니'],['father','명','아버지'],['sister','명','자매'],['brother','명','형제'],['teacher','명','선생님'],['student','명','학생'],['team','명','팀'],['help','동','돕다'],['share','동','나누다'],['give','동','주다'],['take','동','받다'],['thank','동','감사하다'],['smile','동','미소 짓다'],['happy','형','행복한'],['sad','형','슬픈'],['kind','형','친절한'],['brave','형','용감한'],['strong','형','힘이 센'],['safe','형','안전한']],
      middle:[['guardian','명','수호자'],['courage','명','용기'],['trust','명','신뢰'],['promise','명','약속'],['effort','명','노력'],['support','명','지원'],['teamwork','명','협동'],['responsibility','명','책임'],['challenge','명','도전'],['danger','명','위험'],['cooperate','동','협력하다'],['encourage','동','격려하다'],['defend','동','방어하다'],['overcome','동','극복하다'],['respect','동','존중하다'],['succeed','동','성공하다'],['patient','형','참을성 있는'],['confident','형','자신감 있는'],['reliable','형','믿을 만한'],['determined','형','단호한'],["confidence","명","자신감"],["decision","명","결정"],["purpose","명","목적"],["duty","명","의무"],["safety","명","안전"],["rescue","동","구조하다"],["assist","동","도와주다"],["depend","동","의지하다"],["honest","형","정직한"],["loyal","형","충실한"]]},
    {name:'사원 아래 오솔길',desc:'오래된 사원의 흔적을 살펴봐요',
      elementary:[['book','명','책'],['page','명','쪽'],['word','명','단어'],['letter','명','글자'],['story','명','이야기'],['picture','명','그림'],['pencil','명','연필'],['paper','명','종이'],['read','동','읽다'],['write','동','쓰다'],['draw','동','그리다'],['learn','동','배우다'],['ask','동','묻다'],['answer','동','대답하다'],['think','동','생각하다'],['know','동','알다'],['new','형','새로운'],['old','형','오래된'],['easy','형','쉬운'],['hard','형','어려운']],
      middle:[['temple','명','사원'],['ruin','명','유적'],['history','명','역사'],['culture','명','문화'],['tradition','명','전통'],['symbol','명','상징'],['pattern','명','무늬'],['clue','명','단서'],['mystery','명','수수께끼'],['knowledge','명','지식'],['examine','동','조사하다'],['compare','동','비교하다'],['explain','동','설명하다'],['translate','동','번역하다'],['remember','동','기억하다'],['preserve','동','보존하다'],['ancient','형','고대의'],['valuable','형','가치 있는'],['curious','형','호기심이 많은'],['unusual','형','특이한'],["evidence","명","증거"],["record","명","기록"],["legend","명","전설"],["custom","명","관습"],["statue","명","조각상"],["architecture","명","건축"],["research","동","연구하다"],["identify","동","식별하다"],["describe","동","묘사하다"],["historic","형","역사적으로 중요한"]]},
    {name:'크리스탈 사원 입구',desc:'마지막 크리스탈을 깨워 사원 입구에 도착해요',
      elementary:[['crystal','명','크리스탈'],['light','명','빛'],['star','명','별'],['moon','명','달'],['night','명','밤'],['day','명','낮'],['morning','명','아침'],['evening','명','저녁'],['key','명','열쇠'],['box','명','상자'],['gold','명','금'],['purple','형','보라색의'],['bright','형','밝은'],['dark','형','어두운'],['clean','형','깨끗한'],['shine','동','빛나다'],['touch','동','만지다'],['start','동','시작하다'],['finish','동','끝내다'],['win','동','이기다']],
      middle:[['treasure','명','보물'],['reward','명','보상'],['achievement','명','성취'],['wisdom','명','지혜'],['energy','명','에너지'],['reflection','명','반사'],['sparkle','명','반짝임'],['gate','명','관문'],['mission','명','임무'],['victory','명','승리'],['unlock','동','잠금을 풀다'],['activate','동','활성화하다'],['complete','동','완료하다'],['restore','동','복원하다'],['celebrate','동','축하하다'],['advance','동','전진하다'],['brilliant','형','눈부신'],['precious','형','귀중한'],['magical','형','마법의'],['successful','형','성공한'],["success","명","성공"],["goal","명","목표"],["power","명","힘"],["strength","명","강점"],["ability","명","능력"],["opportunity","명","기회"],["accomplish","동","달성하다"],["improve","동","향상시키다"],["glow","동","은은하게 빛나다"],["proud","형","자랑스러운"]]}
  ];
  for(const [index,map] of maps.entries())for(const level of ['elementary','middle']){
    const key=`${level==='elementary'?'e':'s'}${index+8}`;
    window.QUIZ_STAGES[key]={name:map.name,desc:map.desc,learningLevel:level,storyChapter:2,storyStage:index+1,questionCount:map[level].length,words:map[level]};
  }
})();
