window.QUIZ_STAGES=window.QUIZ_STAGES||{};
window.QUIZ_STAGES.s7={
  name:'Stage 7',
  desc:'Day 02 · 30문제',
  words:[
    ['sunshine','명','햇빛, 햇살'],
    ['scratch','동/명','긁다, 할퀴다; 긁힌 자국, 상처'],
    ['documentary','명','다큐멘터리, 기록물'],
    ['fault','명','잘못, 결함, 결점'],
    ['shame','명','수치심, 부끄러움'],
    ['accent','명','억양, 말투'],
    ['wing','명','날개'],
    ['easily','부','쉽게'],
    ['boss','명','상사, 사장'],
    ['arid','형','매우 건조한, 무미건조한'],
    ['discuss','동','의논하다, 상의하다'],
    ['liberal','형','자유로운, 진보적인'],
    ['hierarchy','명','계급(제), 계층'],
    ['cash','명','현금'],
    ['finally','부','마침내'],
    ['novel','명','소설'],
    ['knowledge','명','지식'],
    ['shower','명/동','소나기, 샤워; 샤워하다'],
    ['place','동','두다, 놓다'],
    ['coupon','명','쿠폰, 할인권'],
    ['probably','부','아마(도)'],
    ['supply','동/명','공급하다; 공급'],
    ['graphic','형','생생한, 사실적인'],
    ['backpack','명/동','배낭; 배낭을 지고 걷다'],
    ['vivid','형','생생한, 선명한'],
    ['thumb','명','엄지'],
    ['closely','부','가까이, 밀접하게'],
    ['question','동','질문하다'],
    ['annoy','동','짜증나게 하다'],
    ['collapse','동/명','무너지다, 쓰러지다; 붕괴, 쓰러짐']
  ]
};
