SET local check_function_bodies = off;

CREATE TABLE "public"."character_inventory" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "character_id" uuid                     NOT NULL,
  "item_id"      bigint                   NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "character_inventory_character_id_item_id_key" UNIQUE (character_id, item_id),
  CONSTRAINT "character_inventory_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."character_inventory"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."coin_ledger" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "character_id"  uuid                     NOT NULL,
  "amount"        integer                  NOT NULL,
  "reason"        text                     NOT NULL,
  "stage"         text,
  "game_score_id" bigint,
  "item_id"       bigint,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "coin_ledger_amount_check" CHECK ((amount <> 0)),
  CONSTRAINT "coin_ledger_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."coin_ledger"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."game_characters" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "player"           text                     NOT NULL,
  "name"             text                     NOT NULL,
  "class"            text                     NOT NULL,
  "accent"           text                     NOT NULL DEFAULT 'violet'::text,
  "coins"            integer                  NOT NULL DEFAULT 0,
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "equipped_item_id" bigint,
  CONSTRAINT "game_characters_accent_check" CHECK ((accent = ANY (ARRAY['violet'::text, 'red'::text, 'blue'::text, 'green'::text, 'gold'::text]))),
  CONSTRAINT "game_characters_class_check" CHECK ((class = ANY (ARRAY['warrior'::text, 'mage'::text, 'pugilist'::text, 'ranger'::text]))),
  CONSTRAINT "game_characters_coins_check" CHECK ((coins >= 0)),
  CONSTRAINT "game_characters_name_check" CHECK (((char_length(name) >= 1) AND (char_length(name) <= 16))),
  CONSTRAINT "game_characters_pkey" PRIMARY KEY (id),
  CONSTRAINT "game_characters_player_check"
    CHECK ((((char_length(player) >= 1) AND (char_length(player) <= 12)) AND (player = btrim(player)) AND (player ~ '^[가-힣A-Za-z0-9 _-]+$'::text)))
);

ALTER TABLE "public"."game_characters"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."game_scores" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "player"       text                     NOT NULL,
  "stage"        text                     NOT NULL,
  "correct"      integer                  NOT NULL,
  "total"        integer                  NOT NULL,
  "cleared"      boolean                  NOT NULL DEFAULT false,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "character_id" uuid,
  "duration_ms"  integer,
  "coins_earned" integer                  NOT NULL DEFAULT 0,
  CONSTRAINT "game_scores_coins_earned_check" CHECK ((coins_earned >= 0)),
  CONSTRAINT "game_scores_correct_check" CHECK ((correct >= 0)),
  CONSTRAINT "game_scores_duration_ms_check" CHECK (((duration_ms IS NULL) OR (duration_ms >= 0))),
  CONSTRAINT "game_scores_pkey" PRIMARY KEY (id),
  CONSTRAINT "game_scores_player_check"
    CHECK ((((char_length(player) >= 1) AND (char_length(player) <= 12)) AND (player = btrim(player)) AND (player ~ '^[가-힣A-Za-z0-9 _-]+$'::text))),
  CONSTRAINT "game_scores_total_check" CHECK ((total > 0))
);

ALTER TABLE "public"."game_scores"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reward_redemptions" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "character_id" uuid                     NOT NULL,
  "item_id"      bigint                   NOT NULL,
  "price_paid"   integer                  NOT NULL,
  "status"       text                     NOT NULL DEFAULT 'pending'::text,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "reward_redemptions_pkey" PRIMARY KEY (id),
  CONSTRAINT "reward_redemptions_price_paid_check" CHECK ((price_paid > 0)),
  CONSTRAINT "reward_redemptions_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'fulfilled'::text, 'cancelled'::text])))
);

ALTER TABLE "public"."reward_redemptions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."shop_items" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code"        text                     NOT NULL,
  "name"        text                     NOT NULL,
  "category"    text                     NOT NULL,
  "price"       integer                  NOT NULL,
  "icon"        text                     NOT NULL DEFAULT '🎁'::text,
  "description" text                     NOT NULL DEFAULT ''::text,
  "repeatable"  boolean                  NOT NULL DEFAULT false,
  "active"      boolean                  NOT NULL DEFAULT true,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "shop_items_category_check" CHECK ((category = ANY (ARRAY['avatar'::text, 'gift'::text]))),
  CONSTRAINT "shop_items_code_key" UNIQUE (code),
  CONSTRAINT "shop_items_pkey" PRIMARY KEY (id),
  CONSTRAINT "shop_items_price_check" CHECK ((price > 0))
);

ALTER TABLE "public"."shop_items"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.award_game_result (
  p_character_id uuid,
  p_stage        text,
  p_correct      integer,
  p_total        integer,
  p_cleared      boolean,
  p_duration_ms  integer
)
  RETURNS TABLE (
    game_score_id bigint,
    coins_earned  integer,
    balance       integer,
    personal_best boolean,
    stage_record  boolean
  )
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_player text;
  v_score_id bigint;
  v_reward integer := 0;
  v_question_reward integer := 0;
  v_combo_bonus integer := 0;
  v_clear_bonus integer := 0;
  v_personal boolean := false;
  v_record boolean := false;
  v_prev_personal integer;
  v_prev_global integer;
begin
  select gc.player into v_player
  from public.game_characters gc
  where gc.id = p_character_id
  for update;

  if v_player is null then raise exception 'character not found'; end if;
  if p_total <= 0 or p_correct < 0 or p_correct > p_total then raise exception 'invalid score'; end if;
  if p_cleared and p_correct <> p_total then raise exception 'cleared score must be perfect'; end if;
  if p_duration_ms is null or p_duration_ms < 0 then raise exception 'invalid duration'; end if;

  -- New coin rules:
  -- 1 coin per correct answer
  -- +1 coin at every 5-answer combo milestone (5, 10, 15, ...)
  -- +10 coins for clearing the stage
  v_question_reward := p_correct;
  v_combo_bonus := floor(p_correct / 5.0)::integer;
  v_clear_bonus := case when p_cleared then 10 else 0 end;
  v_reward := v_question_reward + v_combo_bonus + v_clear_bonus;

  -- Keep record flags for ranking/history only. They no longer affect coins.
  if p_cleared then
    select min(gs.duration_ms) into v_prev_personal
    from public.game_scores gs
    where gs.character_id = p_character_id
      and gs.stage = p_stage
      and gs.cleared = true
      and gs.duration_ms is not null;

    select min(gs.duration_ms) into v_prev_global
    from public.game_scores gs
    where gs.stage = p_stage
      and gs.cleared = true
      and gs.duration_ms is not null;

    v_personal := v_prev_personal is null or p_duration_ms < v_prev_personal;
    v_record := v_prev_global is null or p_duration_ms < v_prev_global;
  end if;

  insert into public.game_scores(
    player, stage, correct, total, cleared,
    character_id, duration_ms, coins_earned
  )
  values(
    v_player, p_stage, p_correct, p_total, p_cleared,
    p_character_id, p_duration_ms, v_reward
  )
  returning id into v_score_id;

  if v_reward > 0 then
    update public.game_characters
    set coins = coins + v_reward
    where id = p_character_id;
  end if;

  if v_question_reward > 0 then
    insert into public.coin_ledger(character_id, amount, reason, stage, game_score_id)
    values(p_character_id, v_question_reward, 'question_reward', p_stage, v_score_id);
  end if;

  if v_combo_bonus > 0 then
    insert into public.coin_ledger(character_id, amount, reason, stage, game_score_id)
    values(p_character_id, v_combo_bonus, 'combo_bonus', p_stage, v_score_id);
  end if;

  if v_clear_bonus > 0 then
    insert into public.coin_ledger(character_id, amount, reason, stage, game_score_id)
    values(p_character_id, v_clear_bonus, 'stage_clear_bonus', p_stage, v_score_id);
  end if;

  return query
  select v_score_id, v_reward, gc.coins, v_personal, v_record
  from public.game_characters gc
  where gc.id = p_character_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.equip_avatar_item (
  p_character_id uuid,
  p_item_id      bigint
)
  RETURNS boolean
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  if p_item_id is not null and not exists(
    select 1 from public.character_inventory ci join public.shop_items si on si.id=ci.item_id
    where ci.character_id=p_character_id and ci.item_id=p_item_id and si.category='avatar'
  ) then raise exception 'item not owned'; end if;
  update public.game_characters set equipped_item_id=p_item_id where id=p_character_id;
  if not found then raise exception 'character not found'; end if;
  return true;
end;
$function$;

CREATE OR REPLACE FUNCTION public.purchase_shop_item (
  p_character_id uuid,
  p_item_id      bigint
)
  RETURNS TABLE (
    purchase_type text,
    new_balance   integer,
    redemption_id bigint
  )
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
declare
  v_item public.shop_items%rowtype;
  v_balance integer;
  v_redemption bigint;
begin
  select * into v_item from public.shop_items where id=p_item_id and active=true;
  if v_item.id is null then raise exception 'item not found'; end if;
  select coins into v_balance from public.game_characters where id=p_character_id for update;
  if v_balance is null then raise exception 'character not found'; end if;
  if v_balance < v_item.price then raise exception 'not enough coins'; end if;

  if v_item.category='avatar' then
    if exists(select 1 from public.character_inventory where character_id=p_character_id and item_id=p_item_id) then
      raise exception 'already owned';
    end if;
    insert into public.character_inventory(character_id,item_id) values(p_character_id,p_item_id);
  else
    insert into public.reward_redemptions(character_id,item_id,price_paid,status)
    values(p_character_id,p_item_id,v_item.price,'pending') returning id into v_redemption;
  end if;

  update public.game_characters set coins=coins-v_item.price where id=p_character_id returning coins into v_balance;
  insert into public.coin_ledger(character_id,amount,reason,item_id)
  values(p_character_id,-v_item.price,case when v_item.category='avatar' then 'avatar_purchase' else 'gift_redemption' end,p_item_id);

  return query select v_item.category,v_balance,v_redemption;
end;
$function$;

ALTER TABLE "public"."character_inventory"
  ADD CONSTRAINT "character_inventory_character_id_fkey" FOREIGN KEY (character_id) REFERENCES public.game_characters(id) ON DELETE CASCADE;

ALTER TABLE "public"."coin_ledger"
  ADD CONSTRAINT "coin_ledger_character_id_fkey" FOREIGN KEY (character_id) REFERENCES public.game_characters(id) ON DELETE CASCADE;

ALTER TABLE "public"."game_scores"
  ADD CONSTRAINT "game_scores_character_id_fkey" FOREIGN KEY (character_id) REFERENCES public.game_characters(id) ON DELETE SET NULL;

ALTER TABLE "public"."coin_ledger"
  ADD CONSTRAINT "coin_ledger_game_score_id_fkey" FOREIGN KEY (game_score_id) REFERENCES public.game_scores(id) ON DELETE SET NULL;

ALTER TABLE "public"."reward_redemptions"
  ADD CONSTRAINT "reward_redemptions_character_id_fkey" FOREIGN KEY (character_id) REFERENCES public.game_characters(id) ON DELETE CASCADE;

ALTER TABLE "public"."character_inventory"
  ADD CONSTRAINT "character_inventory_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.shop_items(id);

ALTER TABLE "public"."coin_ledger"
  ADD CONSTRAINT "coin_ledger_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.shop_items(id) ON DELETE SET NULL;

ALTER TABLE "public"."game_characters"
  ADD CONSTRAINT "game_characters_equipped_item_id_fkey" FOREIGN KEY (equipped_item_id) REFERENCES public.shop_items(id) ON DELETE SET NULL;

ALTER TABLE "public"."reward_redemptions"
  ADD CONSTRAINT "reward_redemptions_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.shop_items(id);

CREATE INDEX coin_ledger_character_idx ON public.coin_ledger USING btree (character_id, created_at DESC);

CREATE INDEX game_characters_player_idx ON public.game_characters USING btree (player, created_at);

CREATE INDEX game_scores_character_stage_idx ON public.game_scores USING btree (character_id, stage, cleared, duration_ms);

CREATE INDEX game_scores_player_created_at_idx ON public.game_scores USING btree (player, created_at DESC);

CREATE INDEX reward_redemptions_character_idx ON public.reward_redemptions USING btree (character_id, created_at DESC);

CREATE POLICY "inventory readable" ON "public"."character_inventory"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "ledger readable" ON "public"."coin_ledger"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "characters creatable" ON "public"."game_characters"
  FOR INSERT
  TO "anon"
  WITH CHECK (((coins = 0) AND ((char_length(player) >= 1) AND (char_length(player) <= 12)) AND (player = btrim(player)) AND (player ~ '^[가-힣A-Za-z0-9 _-]+$'::text)));

CREATE POLICY "characters readable" ON "public"."game_characters"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "game scores are readable" ON "public"."game_scores"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "game scores can be inserted" ON "public"."game_scores"
  FOR INSERT
  TO "anon"
  WITH
    CHECK
    ((((char_length(player) >= 1) AND (char_length(player) <= 12)) AND (player = btrim(player)) AND (player ~ '^[가-힣A-Za-z0-9 _-]+$'::text) AND (correct >= 0) AND (total > 0) AND
    (correct <= total)));

CREATE POLICY "redemptions readable" ON "public"."reward_redemptions"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "shop readable" ON "public"."shop_items"
  FOR SELECT
  TO "anon"
  USING ((active = true));

GRANT EXECUTE ON FUNCTION "public"."award_game_result"(uuid, text, integer, integer, boolean, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."equip_avatar_item"(uuid, bigint) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."purchase_shop_item"(uuid, bigint) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."character_inventory" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."character_inventory" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."character_inventory" TO "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."coin_ledger" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."coin_ledger" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."coin_ledger" TO "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."game_characters" FROM "anon";

GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."game_characters" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."game_characters" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."game_scores" TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."reward_redemptions" FROM "anon";

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE "public"."reward_redemptions" TO "anon";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reward_redemptions" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."shop_items" TO "anon", "authenticated", "postgres", "service_role";

