-- Account-owned character rosters and paid character creation tickets.
alter table public.game_characters
  add column if not exists owner_user_id uuid references auth.users(id) on delete cascade;

create index if not exists game_characters_owner_created_idx
  on public.game_characters (owner_user_id, created_at);

create table public.character_creation_tickets (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  purchased_by_character_id uuid not null references public.game_characters(id) on delete cascade,
  consumed_by_character_id uuid unique references public.game_characters(id) on delete set null,
  price_paid integer not null default 1000 check (price_paid = 1000),
  purchased_at timestamptz not null default now(),
  consumed_at timestamptz,
  constraint character_creation_ticket_consumption_check check (
    (consumed_by_character_id is null and consumed_at is null)
    or (consumed_by_character_id is not null and consumed_at is not null)
  )
);

alter table public.character_creation_tickets enable row level security;

create policy "owners read character creation tickets"
on public.character_creation_tickets for select to authenticated
using ((select auth.uid()) = owner_user_id);

drop policy if exists "account characters readable" on public.game_characters;
create policy "account characters readable"
on public.game_characters for select to authenticated
using ((select auth.uid()) = owner_user_id);

drop policy if exists "account inventory readable" on public.character_inventory;
create policy "account inventory readable"
on public.character_inventory for select to authenticated
using (exists (
  select 1 from public.game_characters c
  where c.id = character_inventory.character_id
    and c.owner_user_id = (select auth.uid())
));

drop policy if exists "account redemptions readable" on public.reward_redemptions;
create policy "account redemptions readable"
on public.reward_redemptions for select to authenticated
using (exists (
  select 1 from public.game_characters c
  where c.id = reward_redemptions.character_id
    and c.owner_user_id = (select auth.uid())
));

drop policy if exists "account scores readable" on public.game_scores;
create policy "account scores readable"
on public.game_scores for select to authenticated
using (exists (
  select 1 from public.game_characters c
  where c.id = game_scores.character_id
    and c.owner_user_id = (select auth.uid())
));

drop policy if exists "shop readable by accounts" on public.shop_items;
create policy "shop readable by accounts"
on public.shop_items for select to authenticated
using (active = true);

grant select on public.character_creation_tickets to authenticated;
grant select on public.game_characters, public.character_inventory,
  public.reward_redemptions, public.game_scores, public.shop_items to authenticated;

create or replace function public.purchase_character_creation_ticket(
  p_payer_character_id uuid
)
returns table(ticket_id bigint, new_balance integer, available_tickets integer)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_balance integer;
  v_ticket_id bigint;
begin
  if v_user_id is null then
    raise exception 'authentication required';
  end if;

  select c.coins into v_balance
  from public.game_characters c
  where c.id = p_payer_character_id
    and c.owner_user_id = v_user_id
  for update;

  if v_balance is null then raise exception 'character not found'; end if;
  if v_balance < 1000 then raise exception 'not enough crystals'; end if;

  update public.game_characters
  set coins = coins - 1000
  where id = p_payer_character_id
  returning coins into v_balance;

  insert into public.character_creation_tickets (
    owner_user_id, purchased_by_character_id, price_paid
  ) values (v_user_id, p_payer_character_id, 1000)
  returning id into v_ticket_id;

  insert into public.coin_ledger(character_id, amount, reason)
  values (p_payer_character_id, -1000, 'character_creation_ticket');

  return query
  select v_ticket_id, v_balance, count(*)::integer
  from public.character_creation_tickets t
  where t.owner_user_id = v_user_id and t.consumed_by_character_id is null;
end;
$function$;

create or replace function public.create_account_character(
  p_name text,
  p_class text,
  p_avatar_variant text,
  p_accent text
)
returns public.game_characters
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_player text;
  v_owned_count integer;
  v_ticket_id bigint;
  v_character public.game_characters;
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if p_name is null or char_length(btrim(p_name)) not between 1 and 16 then
    raise exception 'invalid character name';
  end if;
  if p_class not in ('warrior', 'mage', 'pugilist', 'ranger') then
    raise exception 'invalid character class';
  end if;
  if p_avatar_variant not in ('male', 'female') then
    raise exception 'invalid avatar variant';
  end if;
  if p_accent not in ('violet', 'red', 'blue', 'green', 'gold') then
    raise exception 'invalid accent';
  end if;

  -- Serialize roster creation for this account. The profile row always exists
  -- for authenticated users through the auth.users trigger.
  select left(coalesce(nullif(p.login_id, ''), nullif(p.display_name, ''), 'adventurer'), 12)
  into v_player
  from public.profiles p
  where p.user_id = v_user_id
  for update;

  if v_player is null then raise exception 'profile not found'; end if;

  select count(*)::integer into v_owned_count
  from public.game_characters c
  where c.owner_user_id = v_user_id;

  if v_owned_count > 0 then
    select t.id into v_ticket_id
    from public.character_creation_tickets t
    where t.owner_user_id = v_user_id
      and t.consumed_by_character_id is null
    order by t.purchased_at, t.id
    limit 1
    for update;
    if v_ticket_id is null then raise exception 'character creation ticket required'; end if;
  end if;

  insert into public.game_characters (
    owner_user_id, player, name, class, avatar_variant, accent, coins
  ) values (
    v_user_id, v_player, btrim(p_name), p_class, p_avatar_variant, p_accent, 0
  ) returning * into v_character;

  if v_ticket_id is not null then
    update public.character_creation_tickets
    set consumed_by_character_id = v_character.id, consumed_at = now()
    where id = v_ticket_id;
  end if;

  return v_character;
end;
$function$;

revoke all on function public.purchase_character_creation_ticket(uuid) from public, anon;
revoke all on function public.create_account_character(text, text, text, text) from public, anon;
grant execute on function public.purchase_character_creation_ticket(uuid) to authenticated;
grant execute on function public.create_account_character(text, text, text, text) to authenticated;

comment on table public.character_creation_tickets is
'One-use account-owned tickets. The first account character is free; every later character consumes one 1,000-crystal ticket.';
