create table if not exists public.stage_crystal_reward_claims (
  id bigint generated by default as identity primary key,
  owner_user_id uuid references auth.users(id) on delete cascade,
  guest_character_id uuid references public.game_characters(id) on delete cascade,
  stage text not null,
  first_game_score_id bigint not null references public.game_scores(id) on delete cascade,
  treasure_claimed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint stage_crystal_reward_claims_identity_check check (
    (owner_user_id is not null and guest_character_id is null) or
    (owner_user_id is null and guest_character_id is not null)
  )
);

create unique index if not exists stage_crystal_reward_claims_owner_stage_uidx
  on public.stage_crystal_reward_claims(owner_user_id, stage) where owner_user_id is not null;
create unique index if not exists stage_crystal_reward_claims_guest_stage_uidx
  on public.stage_crystal_reward_claims(guest_character_id, stage) where guest_character_id is not null;
alter table public.stage_crystal_reward_claims enable row level security;
revoke all on public.stage_crystal_reward_claims from public, anon, authenticated;

create or replace function public.award_game_result(
  p_character_id uuid,
  p_stage text,
  p_correct integer,
  p_total integer,
  p_cleared boolean,
  p_duration_ms integer
)
returns table(game_score_id bigint, coins_earned integer, balance integer, personal_best boolean, stage_record boolean)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_player text;
  v_class text;
  v_owner_user_id uuid;
  v_request_user_id uuid := auth.uid();
  v_score_id bigint;
  v_question_reward integer;
  v_combo_bonus integer;
  v_clear_bonus integer;
  v_reward integer;
  v_balance integer;
  v_personal boolean := false;
  v_record boolean := false;
  v_prev_personal integer;
  v_prev_global integer;
  v_first_score_id bigint;
begin
  select c.player, c.class, c.owner_user_id into v_player, v_class, v_owner_user_id
  from public.game_characters c where c.id = p_character_id for update;
  if v_player is null then raise exception 'character not found'; end if;
  if v_owner_user_id is not null and v_request_user_id is distinct from v_owner_user_id then raise exception 'character not found'; end if;
  if v_owner_user_id is null and v_request_user_id is not null then raise exception 'character not found'; end if;
  if p_total <= 0 or p_correct < 0 or p_correct > p_total then raise exception 'invalid score'; end if;
  if p_cleared and p_correct <> p_total then raise exception 'cleared score must be perfect'; end if;
  if p_duration_ms is null or p_duration_ms < 0 then raise exception 'invalid duration'; end if;

  -- Serialize stage payouts across every character owned by the same account.
  if v_owner_user_id is not null then
    perform 1 from public.profiles p where p.user_id = v_owner_user_id for update;
    select c.id into v_first_score_id from public.stage_crystal_reward_claims c
    where c.owner_user_id = v_owner_user_id and c.stage = p_stage;
  else
    select c.id into v_first_score_id from public.stage_crystal_reward_claims c
    where c.guest_character_id = p_character_id and c.stage = p_stage;
  end if;

  v_question_reward := p_correct;
  v_combo_bonus := floor(p_correct / case when v_class = 'pugilist' then 3.0 else 5.0 end)::integer;
  v_clear_bonus := case when p_cleared then 10 else 0 end;
  v_reward := case when v_first_score_id is null then v_question_reward + v_combo_bonus + v_clear_bonus else 0 end;

  if p_cleared then
    select min(s.duration_ms) into v_prev_personal from public.game_scores s
    where s.character_id = p_character_id and s.stage = p_stage and s.cleared and s.duration_ms is not null;
    select min(s.duration_ms) into v_prev_global from public.game_scores s
    where s.stage = p_stage and s.cleared and s.duration_ms is not null;
    v_personal := v_prev_personal is null or p_duration_ms < v_prev_personal;
    v_record := v_prev_global is null or p_duration_ms < v_prev_global;
  end if;

  insert into public.game_scores(player, stage, correct, total, cleared, character_id, duration_ms, coins_earned)
  values(v_player, p_stage, p_correct, p_total, p_cleared, p_character_id, p_duration_ms, v_reward)
  returning id into v_score_id;

  if v_reward > 0 then
    if v_owner_user_id is not null then
      insert into public.stage_crystal_reward_claims(owner_user_id, stage, first_game_score_id)
      values(v_owner_user_id, p_stage, v_score_id);
      update public.profiles set crystal_balance = crystal_balance + v_reward, updated_at = now()
      where user_id = v_owner_user_id returning crystal_balance into v_balance;
    else
      insert into public.stage_crystal_reward_claims(guest_character_id, stage, first_game_score_id)
      values(p_character_id, p_stage, v_score_id);
      update public.game_characters set coins = coins + v_reward
      where id = p_character_id returning coins into v_balance;
    end if;
    if v_question_reward > 0 then insert into public.coin_ledger(character_id, amount, reason, stage, game_score_id) values(p_character_id, v_question_reward, 'question_reward', p_stage, v_score_id); end if;
    if v_combo_bonus > 0 then insert into public.coin_ledger(character_id, amount, reason, stage, game_score_id) values(p_character_id, v_combo_bonus, 'combo_bonus', p_stage, v_score_id); end if;
    if v_clear_bonus > 0 then insert into public.coin_ledger(character_id, amount, reason, stage, game_score_id) values(p_character_id, v_clear_bonus, 'stage_clear_bonus', p_stage, v_score_id); end if;
  elsif v_owner_user_id is not null then
    select p.crystal_balance into v_balance from public.profiles p where p.user_id = v_owner_user_id;
  else
    select c.coins into v_balance from public.game_characters c where c.id = p_character_id;
  end if;
  return query select v_score_id, v_reward, v_balance, v_personal, v_record;
end;
$function$;

create or replace function public.claim_stage_treasure(p_character_id uuid, p_game_score_id bigint)
returns table(reward integer, balance integer)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_class text;
  v_owner_user_id uuid;
  v_request_user_id uuid := auth.uid();
  v_stage text;
  v_claim_score_id bigint;
  v_min integer;
  v_reward integer := 0;
begin
  select c.class, c.owner_user_id into v_class, v_owner_user_id
  from public.game_characters c where c.id = p_character_id for update;
  if v_class is null then raise exception 'character not found'; end if;
  if v_owner_user_id is not null and v_request_user_id is distinct from v_owner_user_id then raise exception 'character not found'; end if;
  if v_owner_user_id is null and v_request_user_id is not null then raise exception 'character not found'; end if;

  select s.stage into v_stage from public.game_scores s
  where s.id = p_game_score_id and s.character_id = p_character_id and s.cleared = true and s.treasure_claimed = false
  for update;
  if not found then raise exception 'treasure unavailable or already claimed'; end if;
  update public.game_scores set treasure_claimed = true where id = p_game_score_id;

  if v_owner_user_id is not null then
    perform 1 from public.profiles p where p.user_id = v_owner_user_id for update;
    select c.first_game_score_id into v_claim_score_id from public.stage_crystal_reward_claims c
    where c.owner_user_id = v_owner_user_id and c.stage = v_stage and c.treasure_claimed = false
    for update;
    if v_claim_score_id = p_game_score_id then
      v_min := case when v_class = 'ranger' then 20 else 10 end;
      v_reward := v_min + floor(random() * (31 - v_min))::integer;
      update public.stage_crystal_reward_claims set treasure_claimed = true
      where owner_user_id = v_owner_user_id and stage = v_stage;
      update public.profiles set crystal_balance = crystal_balance + v_reward, updated_at = now()
      where user_id = v_owner_user_id returning crystal_balance into balance;
    else
      select p.crystal_balance into balance from public.profiles p where p.user_id = v_owner_user_id;
    end if;
  else
    select c.first_game_score_id into v_claim_score_id from public.stage_crystal_reward_claims c
    where c.guest_character_id = p_character_id and c.stage = v_stage and c.treasure_claimed = false
    for update;
    if v_claim_score_id = p_game_score_id then
      v_min := case when v_class = 'ranger' then 20 else 10 end;
      v_reward := v_min + floor(random() * (31 - v_min))::integer;
      update public.stage_crystal_reward_claims set treasure_claimed = true
      where guest_character_id = p_character_id and stage = v_stage;
      update public.game_characters set coins = coins + v_reward
      where id = p_character_id returning coins into balance;
    else
      select c.coins into balance from public.game_characters c where c.id = p_character_id;
    end if;
  end if;

  if v_reward > 0 then
    insert into public.coin_ledger(character_id, amount, reason, game_score_id)
    values(p_character_id, v_reward, 'treasure_reward', p_game_score_id);
  end if;
  reward := v_reward;
  return next;
end;
$function$;

revoke all on function public.award_game_result(uuid, text, integer, integer, boolean, integer) from public;
revoke all on function public.claim_stage_treasure(uuid, bigint) from public;
grant execute on function public.award_game_result(uuid, text, integer, integer, boolean, integer) to anon, authenticated;
grant execute on function public.claim_stage_treasure(uuid, bigint) to anon, authenticated;
